language: php
php:
    - 5.3

env:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  allow_failures:
    - env: DB=SQLITE CORE_RELEASE=master 
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.4
      env: DB=SQLITE CORE_RELEASE=3.1
    - php: 5.4
      env: DB=SQLITE CORE_RELEASE=master    

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - "vendor/bin/phpunit -c importexport/phpunit.xml.dist"
